version: "3"
services:
  frontend:
    build:
      context: .
    container_name: frontend
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm start
    ports:
      - "5173:5173"
volumes:
  data: